//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagement.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Views_Home__Form_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Views_Home__Form_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskManagement.Resources.Views.Home._Form.ru", typeof(Views_Home__Form_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задача создана!.
        /// </summary>
        internal static string CreateMainTaskAlert {
            get {
                return ResourceManager.GetString("CreateMainTaskAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать задачу.
        /// </summary>
        internal static string CreateMainTaskButton {
            get {
                return ResourceManager.GetString("CreateMainTaskButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подзадача создана!.
        /// </summary>
        internal static string CreateSubTaskAlert {
            get {
                return ResourceManager.GetString("CreateSubTaskAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать подзадачу.
        /// </summary>
        internal static string CreateSubTaskButton {
            get {
                return ResourceManager.GetString("CreateSubTaskButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо выбрать задачу - родителя!.
        /// </summary>
        internal static string CreateSubTaskErrorAlert {
            get {
                return ResourceManager.GetString("CreateSubTaskErrorAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задача удалена!.
        /// </summary>
        internal static string RemoveTaskAlert {
            get {
                return ResourceManager.GetString("RemoveTaskAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string RemoveTaskButton {
            get {
                return ResourceManager.GetString("RemoveTaskButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо выбрать задачу.
        /// </summary>
        internal static string RemoveTaskChoiceErrorAlert {
            get {
                return ResourceManager.GetString("RemoveTaskChoiceErrorAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У этой задачи есть подзадачи!.
        /// </summary>
        internal static string RemoveTaskSubTasksErrorAlert {
            get {
                return ResourceManager.GetString("RemoveTaskSubTasksErrorAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задача обновлена!.
        /// </summary>
        internal static string SaveTaskChangesAlert {
            get {
                return ResourceManager.GetString("SaveTaskChangesAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        internal static string SaveTaskChangesButton {
            get {
                return ResourceManager.GetString("SaveTaskChangesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо выбрать задачу!.
        /// </summary>
        internal static string SaveTaskChangesErrorAlert {
            get {
                return ResourceManager.GetString("SaveTaskChangesErrorAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прогнозируемое время завершения:.
        /// </summary>
        internal static string TaskCompletionTime {
            get {
                return ResourceManager.GetString("TaskCompletionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущее время выполнения задачи(в часах):.
        /// </summary>
        internal static string TaskCurRunTime {
            get {
                return ResourceManager.GetString("TaskCurRunTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание:.
        /// </summary>
        internal static string TaskDescription {
            get {
                return ResourceManager.GetString("TaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о задаче:.
        /// </summary>
        internal static string TaskInfoLabel {
            get {
                return ResourceManager.GetString("TaskInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название:.
        /// </summary>
        internal static string TaskName {
            get {
                return ResourceManager.GetString("TaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполнители:.
        /// </summary>
        internal static string TaskPerformers {
            get {
                return ResourceManager.GetString("TaskPerformers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ожидаемое время выполнения задачи(в часах):.
        /// </summary>
        internal static string TaskPredictRunTime {
            get {
                return ResourceManager.GetString("TaskPredictRunTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время создания:.
        /// </summary>
        internal static string TaskRegTime {
            get {
                return ResourceManager.GetString("TaskRegTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус:.
        /// </summary>
        internal static string TaskStatus {
            get {
                return ResourceManager.GetString("TaskStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назначена.
        /// </summary>
        internal static string TaskStatusAppointed {
            get {
                return ResourceManager.GetString("TaskStatusAppointed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнена.
        /// </summary>
        internal static string TaskStatusCompleted {
            get {
                return ResourceManager.GetString("TaskStatusCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполняется.
        /// </summary>
        internal static string TaskStatusInProgress {
            get {
                return ResourceManager.GetString("TaskStatusInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приостановлена.
        /// </summary>
        internal static string TaskStatusPaused {
            get {
                return ResourceManager.GetString("TaskStatusPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущее время выполнения подзадач(в часах):.
        /// </summary>
        internal static string TaskSubTasksCurTime {
            get {
                return ResourceManager.GetString("TaskSubTasksCurTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ожидаемое время выполнения подзадач(в часах):.
        /// </summary>
        internal static string TaskSubTasksPredictTime {
            get {
                return ResourceManager.GetString("TaskSubTasksPredictTime", resourceCulture);
            }
        }
    }
}
