//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagement.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Views_Home__Form_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Views_Home__Form_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskManagement.Resources.Views.Home._Form.en", typeof(Views_Home__Form_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task created!.
        /// </summary>
        internal static string CreateMainTaskAlert {
            get {
                return ResourceManager.GetString("CreateMainTaskAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сreate main task.
        /// </summary>
        internal static string CreateMainTaskButton {
            get {
                return ResourceManager.GetString("CreateMainTaskButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtask created!.
        /// </summary>
        internal static string CreateSubTaskAlert {
            get {
                return ResourceManager.GetString("CreateSubTaskAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create subtask.
        /// </summary>
        internal static string CreateSubTaskButton {
            get {
                return ResourceManager.GetString("CreateSubTaskButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is necessary to choose the task - the parent!.
        /// </summary>
        internal static string CreateSubTaskErrorAlert {
            get {
                return ResourceManager.GetString("CreateSubTaskErrorAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The task has been deleted!.
        /// </summary>
        internal static string RemoveTaskAlert {
            get {
                return ResourceManager.GetString("RemoveTaskAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string RemoveTaskButton {
            get {
                return ResourceManager.GetString("RemoveTaskButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a task!.
        /// </summary>
        internal static string RemoveTaskChoiceErrorAlert {
            get {
                return ResourceManager.GetString("RemoveTaskChoiceErrorAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This task has subtasks!.
        /// </summary>
        internal static string RemoveTaskSubTasksErrorAlert {
            get {
                return ResourceManager.GetString("RemoveTaskSubTasksErrorAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The task has been updated!.
        /// </summary>
        internal static string SaveTaskChangesAlert {
            get {
                return ResourceManager.GetString("SaveTaskChangesAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveTaskChangesButton {
            get {
                return ResourceManager.GetString("SaveTaskChangesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a task!.
        /// </summary>
        internal static string SaveTaskChangesErrorAlert {
            get {
                return ResourceManager.GetString("SaveTaskChangesErrorAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predicted completion time:.
        /// </summary>
        internal static string TaskCompletionTime {
            get {
                return ResourceManager.GetString("TaskCompletionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current task execution time (in hours):.
        /// </summary>
        internal static string TaskCurRunTime {
            get {
                return ResourceManager.GetString("TaskCurRunTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string TaskDescription {
            get {
                return ResourceManager.GetString("TaskDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Info:.
        /// </summary>
        internal static string TaskInfoLabel {
            get {
                return ResourceManager.GetString("TaskInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string TaskName {
            get {
                return ResourceManager.GetString("TaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performers:.
        /// </summary>
        internal static string TaskPerformers {
            get {
                return ResourceManager.GetString("TaskPerformers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated time to complete the task (in hours):.
        /// </summary>
        internal static string TaskPredictRunTime {
            get {
                return ResourceManager.GetString("TaskPredictRunTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time of creation:.
        /// </summary>
        internal static string TaskRegTime {
            get {
                return ResourceManager.GetString("TaskRegTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string TaskStatus {
            get {
                return ResourceManager.GetString("TaskStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointed.
        /// </summary>
        internal static string TaskStatusAppointed {
            get {
                return ResourceManager.GetString("TaskStatusAppointed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string TaskStatusCompleted {
            get {
                return ResourceManager.GetString("TaskStatusCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        internal static string TaskStatusInProgress {
            get {
                return ResourceManager.GetString("TaskStatusInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string TaskStatusPaused {
            get {
                return ResourceManager.GetString("TaskStatusPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current execution time of subtasks (in hours):.
        /// </summary>
        internal static string TaskSubTasksCurTime {
            get {
                return ResourceManager.GetString("TaskSubTasksCurTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated time to complete subtasks (in hours):.
        /// </summary>
        internal static string TaskSubTasksPredictTime {
            get {
                return ResourceManager.GetString("TaskSubTasksPredictTime", resourceCulture);
            }
        }
    }
}
